### PR TITLE
codeowners file added

### PR DESCRIPTION
**Pull request by pritamrajput**
#codeowner file

I have added a code owners file to our repository

### CODE REVIEW

**Comment by ghost** [comment]
Reviewing this right now, let's see...

**Review by ghost — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by pritamrajput** [comment]
I have made changes

**Review by ghost — CHANGES_REQUESTED** [review]
Seems like the `CODEOWNERS` file is missing the right content. Just remove Carl from the file and keep the rest. Could you fix that and push the changes?

**Comment by pritamrajput** [comment]
I have made changes

**Review by pritamrajput — COMMENTED** [review]
I have made changes

**Comment by pritamrajput** [comment]
I have made changes

**Comment by pritamrajput** [comment]
I want to make few changes

**Review by pritamrajput — COMMENTED** [review]
I have made changes

**Comment by pritamrajput** [comment]
I have made changes

**Review by ghost — APPROVED** [review]
Approved! Go ahead and merge this PR. Quickly now.

**Pull request merged**
